// source: mediapipe/framework/formats/detection.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var mediapipe_framework_formats_location_data_pb = require('../../../mediapipe/framework/formats/location_data_pb.js');
goog.object.extend(proto, mediapipe_framework_formats_location_data_pb);
goog.exportSymbol('proto.mediapipe.Detection', null, global);
goog.exportSymbol('proto.mediapipe.Detection.AssociatedDetection', null, global);
goog.exportSymbol('proto.mediapipe.DetectionList', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mediapipe.Detection = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.mediapipe.Detection.repeatedFields_, null);
};
goog.inherits(proto.mediapipe.Detection, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mediapipe.Detection.displayName = 'proto.mediapipe.Detection';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mediapipe.Detection.AssociatedDetection = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mediapipe.Detection.AssociatedDetection, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mediapipe.Detection.AssociatedDetection.displayName = 'proto.mediapipe.Detection.AssociatedDetection';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mediapipe.DetectionList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.mediapipe.DetectionList.repeatedFields_, null);
};
goog.inherits(proto.mediapipe.DetectionList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mediapipe.DetectionList.displayName = 'proto.mediapipe.DetectionList';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.mediapipe.Detection.repeatedFields_ = [1,2,3,8,9];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mediapipe.Detection.prototype.toObject = function(opt_includeInstance) {
  return proto.mediapipe.Detection.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mediapipe.Detection} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mediapipe.Detection.toObject = function(includeInstance, msg) {
  var f, obj = {
    labelList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    labelIdList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    scoreList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 3)) == null ? undefined : f,
    locationData: (f = msg.getLocationData()) && mediapipe_framework_formats_location_data_pb.LocationData.toObject(includeInstance, f),
    featureTag: (f = jspb.Message.getField(msg, 5)) == null ? undefined : f,
    trackId: (f = jspb.Message.getField(msg, 6)) == null ? undefined : f,
    detectionId: (f = jspb.Message.getField(msg, 7)) == null ? undefined : f,
    associatedDetectionsList: jspb.Message.toObjectList(msg.getAssociatedDetectionsList(),
    proto.mediapipe.Detection.AssociatedDetection.toObject, includeInstance),
    displayNameList: (f = jspb.Message.getRepeatedField(msg, 9)) == null ? undefined : f,
    timestampUsec: (f = jspb.Message.getField(msg, 10)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mediapipe.Detection}
 */
proto.mediapipe.Detection.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mediapipe.Detection;
  return proto.mediapipe.Detection.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mediapipe.Detection} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mediapipe.Detection}
 */
proto.mediapipe.Detection.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addLabel(value);
      break;
    case 2:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
      msg.setLabelIdList(value);
      break;
    case 3:
      var value = /** @type {!Array<number>} */ (reader.readPackedFloat());
      msg.setScoreList(value);
      break;
    case 4:
      var value = new mediapipe_framework_formats_location_data_pb.LocationData;
      reader.readMessage(value,mediapipe_framework_formats_location_data_pb.LocationData.deserializeBinaryFromReader);
      msg.setLocationData(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setFeatureTag(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setTrackId(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDetectionId(value);
      break;
    case 8:
      var value = new proto.mediapipe.Detection.AssociatedDetection;
      reader.readMessage(value,proto.mediapipe.Detection.AssociatedDetection.deserializeBinaryFromReader);
      msg.addAssociatedDetections(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.addDisplayName(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestampUsec(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mediapipe.Detection.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mediapipe.Detection.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mediapipe.Detection} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mediapipe.Detection.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLabelList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getLabelIdList();
  if (f.length > 0) {
    writer.writePackedInt32(
      2,
      f
    );
  }
  f = message.getScoreList();
  if (f.length > 0) {
    writer.writePackedFloat(
      3,
      f
    );
  }
  f = message.getLocationData();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      mediapipe_framework_formats_location_data_pb.LocationData.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeString(
      6,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getAssociatedDetectionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      proto.mediapipe.Detection.AssociatedDetection.serializeBinaryToWriter
    );
  }
  f = message.getDisplayNameList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      9,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 10));
  if (f != null) {
    writer.writeInt64(
      10,
      f
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mediapipe.Detection.AssociatedDetection.prototype.toObject = function(opt_includeInstance) {
  return proto.mediapipe.Detection.AssociatedDetection.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mediapipe.Detection.AssociatedDetection} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mediapipe.Detection.AssociatedDetection.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    confidence: (f = jspb.Message.getOptionalFloatingPointField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mediapipe.Detection.AssociatedDetection}
 */
proto.mediapipe.Detection.AssociatedDetection.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mediapipe.Detection.AssociatedDetection;
  return proto.mediapipe.Detection.AssociatedDetection.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mediapipe.Detection.AssociatedDetection} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mediapipe.Detection.AssociatedDetection}
 */
proto.mediapipe.Detection.AssociatedDetection.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setConfidence(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mediapipe.Detection.AssociatedDetection.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mediapipe.Detection.AssociatedDetection.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mediapipe.Detection.AssociatedDetection} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mediapipe.Detection.AssociatedDetection.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeFloat(
      2,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.mediapipe.Detection.AssociatedDetection.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.mediapipe.Detection.AssociatedDetection} returns this
 */
proto.mediapipe.Detection.AssociatedDetection.prototype.setId = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mediapipe.Detection.AssociatedDetection} returns this
 */
proto.mediapipe.Detection.AssociatedDetection.prototype.clearId = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.Detection.AssociatedDetection.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional float confidence = 2;
 * @return {number}
 */
proto.mediapipe.Detection.AssociatedDetection.prototype.getConfidence = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.mediapipe.Detection.AssociatedDetection} returns this
 */
proto.mediapipe.Detection.AssociatedDetection.prototype.setConfidence = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mediapipe.Detection.AssociatedDetection} returns this
 */
proto.mediapipe.Detection.AssociatedDetection.prototype.clearConfidence = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.Detection.AssociatedDetection.prototype.hasConfidence = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated string label = 1;
 * @return {!Array<string>}
 */
proto.mediapipe.Detection.prototype.getLabelList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.mediapipe.Detection} returns this
 */
proto.mediapipe.Detection.prototype.setLabelList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.mediapipe.Detection} returns this
 */
proto.mediapipe.Detection.prototype.addLabel = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.mediapipe.Detection} returns this
 */
proto.mediapipe.Detection.prototype.clearLabelList = function() {
  return this.setLabelList([]);
};


/**
 * repeated int32 label_id = 2;
 * @return {!Array<number>}
 */
proto.mediapipe.Detection.prototype.getLabelIdList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.mediapipe.Detection} returns this
 */
proto.mediapipe.Detection.prototype.setLabelIdList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.mediapipe.Detection} returns this
 */
proto.mediapipe.Detection.prototype.addLabelId = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.mediapipe.Detection} returns this
 */
proto.mediapipe.Detection.prototype.clearLabelIdList = function() {
  return this.setLabelIdList([]);
};


/**
 * repeated float score = 3;
 * @return {!Array<number>}
 */
proto.mediapipe.Detection.prototype.getScoreList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 3));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.mediapipe.Detection} returns this
 */
proto.mediapipe.Detection.prototype.setScoreList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.mediapipe.Detection} returns this
 */
proto.mediapipe.Detection.prototype.addScore = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.mediapipe.Detection} returns this
 */
proto.mediapipe.Detection.prototype.clearScoreList = function() {
  return this.setScoreList([]);
};


/**
 * optional LocationData location_data = 4;
 * @return {?proto.mediapipe.LocationData}
 */
proto.mediapipe.Detection.prototype.getLocationData = function() {
  return /** @type{?proto.mediapipe.LocationData} */ (
    jspb.Message.getWrapperField(this, mediapipe_framework_formats_location_data_pb.LocationData, 4));
};


/**
 * @param {?proto.mediapipe.LocationData|undefined} value
 * @return {!proto.mediapipe.Detection} returns this
*/
proto.mediapipe.Detection.prototype.setLocationData = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mediapipe.Detection} returns this
 */
proto.mediapipe.Detection.prototype.clearLocationData = function() {
  return this.setLocationData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.Detection.prototype.hasLocationData = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string feature_tag = 5;
 * @return {string}
 */
proto.mediapipe.Detection.prototype.getFeatureTag = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.mediapipe.Detection} returns this
 */
proto.mediapipe.Detection.prototype.setFeatureTag = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mediapipe.Detection} returns this
 */
proto.mediapipe.Detection.prototype.clearFeatureTag = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.Detection.prototype.hasFeatureTag = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional string track_id = 6;
 * @return {string}
 */
proto.mediapipe.Detection.prototype.getTrackId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.mediapipe.Detection} returns this
 */
proto.mediapipe.Detection.prototype.setTrackId = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mediapipe.Detection} returns this
 */
proto.mediapipe.Detection.prototype.clearTrackId = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.Detection.prototype.hasTrackId = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional int64 detection_id = 7;
 * @return {number}
 */
proto.mediapipe.Detection.prototype.getDetectionId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.mediapipe.Detection} returns this
 */
proto.mediapipe.Detection.prototype.setDetectionId = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mediapipe.Detection} returns this
 */
proto.mediapipe.Detection.prototype.clearDetectionId = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.Detection.prototype.hasDetectionId = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * repeated AssociatedDetection associated_detections = 8;
 * @return {!Array<!proto.mediapipe.Detection.AssociatedDetection>}
 */
proto.mediapipe.Detection.prototype.getAssociatedDetectionsList = function() {
  return /** @type{!Array<!proto.mediapipe.Detection.AssociatedDetection>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.mediapipe.Detection.AssociatedDetection, 8));
};


/**
 * @param {!Array<!proto.mediapipe.Detection.AssociatedDetection>} value
 * @return {!proto.mediapipe.Detection} returns this
*/
proto.mediapipe.Detection.prototype.setAssociatedDetectionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.mediapipe.Detection.AssociatedDetection=} opt_value
 * @param {number=} opt_index
 * @return {!proto.mediapipe.Detection.AssociatedDetection}
 */
proto.mediapipe.Detection.prototype.addAssociatedDetections = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.mediapipe.Detection.AssociatedDetection, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.mediapipe.Detection} returns this
 */
proto.mediapipe.Detection.prototype.clearAssociatedDetectionsList = function() {
  return this.setAssociatedDetectionsList([]);
};


/**
 * repeated string display_name = 9;
 * @return {!Array<string>}
 */
proto.mediapipe.Detection.prototype.getDisplayNameList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 9));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.mediapipe.Detection} returns this
 */
proto.mediapipe.Detection.prototype.setDisplayNameList = function(value) {
  return jspb.Message.setField(this, 9, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.mediapipe.Detection} returns this
 */
proto.mediapipe.Detection.prototype.addDisplayName = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 9, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.mediapipe.Detection} returns this
 */
proto.mediapipe.Detection.prototype.clearDisplayNameList = function() {
  return this.setDisplayNameList([]);
};


/**
 * optional int64 timestamp_usec = 10;
 * @return {number}
 */
proto.mediapipe.Detection.prototype.getTimestampUsec = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.mediapipe.Detection} returns this
 */
proto.mediapipe.Detection.prototype.setTimestampUsec = function(value) {
  return jspb.Message.setField(this, 10, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mediapipe.Detection} returns this
 */
proto.mediapipe.Detection.prototype.clearTimestampUsec = function() {
  return jspb.Message.setField(this, 10, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.Detection.prototype.hasTimestampUsec = function() {
  return jspb.Message.getField(this, 10) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.mediapipe.DetectionList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mediapipe.DetectionList.prototype.toObject = function(opt_includeInstance) {
  return proto.mediapipe.DetectionList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mediapipe.DetectionList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mediapipe.DetectionList.toObject = function(includeInstance, msg) {
  var f, obj = {
    detectionList: jspb.Message.toObjectList(msg.getDetectionList(),
    proto.mediapipe.Detection.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mediapipe.DetectionList}
 */
proto.mediapipe.DetectionList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mediapipe.DetectionList;
  return proto.mediapipe.DetectionList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mediapipe.DetectionList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mediapipe.DetectionList}
 */
proto.mediapipe.DetectionList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.mediapipe.Detection;
      reader.readMessage(value,proto.mediapipe.Detection.deserializeBinaryFromReader);
      msg.addDetection(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mediapipe.DetectionList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mediapipe.DetectionList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mediapipe.DetectionList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mediapipe.DetectionList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDetectionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.mediapipe.Detection.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Detection detection = 1;
 * @return {!Array<!proto.mediapipe.Detection>}
 */
proto.mediapipe.DetectionList.prototype.getDetectionList = function() {
  return /** @type{!Array<!proto.mediapipe.Detection>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.mediapipe.Detection, 1));
};


/**
 * @param {!Array<!proto.mediapipe.Detection>} value
 * @return {!proto.mediapipe.DetectionList} returns this
*/
proto.mediapipe.DetectionList.prototype.setDetectionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.mediapipe.Detection=} opt_value
 * @param {number=} opt_index
 * @return {!proto.mediapipe.Detection}
 */
proto.mediapipe.DetectionList.prototype.addDetection = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.mediapipe.Detection, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.mediapipe.DetectionList} returns this
 */
proto.mediapipe.DetectionList.prototype.clearDetectionList = function() {
  return this.setDetectionList([]);
};


goog.object.extend(exports, proto.mediapipe);
