// source: mediapipe/framework/formats/time_series_header.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.mediapipe.MultiStreamTimeSeriesHeader', null, global);
goog.exportSymbol('proto.mediapipe.TimeSeriesHeader', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mediapipe.TimeSeriesHeader = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 6, null, null);
};
goog.inherits(proto.mediapipe.TimeSeriesHeader, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mediapipe.TimeSeriesHeader.displayName = 'proto.mediapipe.TimeSeriesHeader';
}

/**
 * The extensions registered with this message class. This is a map of
 * extension field number to fieldInfo object.
 *
 * For example:
 *     { 123: {fieldIndex: 123, fieldName: {my_field_name: 0}, ctor: proto.example.MyMessage} }
 *
 * fieldName contains the JsCompiler renamed field name property so that it
 * works in OPTIMIZED mode.
 *
 * @type {!Object<number, jspb.ExtensionFieldInfo>}
 */
proto.mediapipe.TimeSeriesHeader.extensions = {};


/**
 * The extensions registered with this message class. This is a map of
 * extension field number to fieldInfo object.
 *
 * For example:
 *     { 123: {fieldIndex: 123, fieldName: {my_field_name: 0}, ctor: proto.example.MyMessage} }
 *
 * fieldName contains the JsCompiler renamed field name property so that it
 * works in OPTIMIZED mode.
 *
 * @type {!Object<number, jspb.ExtensionFieldBinaryInfo>}
 */
proto.mediapipe.TimeSeriesHeader.extensionsBinary = {};

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mediapipe.MultiStreamTimeSeriesHeader = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mediapipe.MultiStreamTimeSeriesHeader, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mediapipe.MultiStreamTimeSeriesHeader.displayName = 'proto.mediapipe.MultiStreamTimeSeriesHeader';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mediapipe.TimeSeriesHeader.prototype.toObject = function(opt_includeInstance) {
  return proto.mediapipe.TimeSeriesHeader.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mediapipe.TimeSeriesHeader} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mediapipe.TimeSeriesHeader.toObject = function(includeInstance, msg) {
  var f, obj = {
    sampleRate: (f = jspb.Message.getOptionalFloatingPointField(msg, 1)) == null ? undefined : f,
    numChannels: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    numSamples: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    packetRate: (f = jspb.Message.getOptionalFloatingPointField(msg, 4)) == null ? undefined : f,
    audioSampleRate: (f = jspb.Message.getOptionalFloatingPointField(msg, 5)) == null ? undefined : f
  };

  jspb.Message.toObjectExtension(/** @type {!jspb.Message} */ (msg), obj,
      proto.mediapipe.TimeSeriesHeader.extensions, proto.mediapipe.TimeSeriesHeader.prototype.getExtension,
      includeInstance);
  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mediapipe.TimeSeriesHeader}
 */
proto.mediapipe.TimeSeriesHeader.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mediapipe.TimeSeriesHeader;
  return proto.mediapipe.TimeSeriesHeader.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mediapipe.TimeSeriesHeader} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mediapipe.TimeSeriesHeader}
 */
proto.mediapipe.TimeSeriesHeader.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setSampleRate(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNumChannels(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNumSamples(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setPacketRate(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAudioSampleRate(value);
      break;
    default:
      jspb.Message.readBinaryExtension(msg, reader,
        proto.mediapipe.TimeSeriesHeader.extensionsBinary,
        proto.mediapipe.TimeSeriesHeader.prototype.getExtension,
        proto.mediapipe.TimeSeriesHeader.prototype.setExtension);
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mediapipe.TimeSeriesHeader.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mediapipe.TimeSeriesHeader.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mediapipe.TimeSeriesHeader} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mediapipe.TimeSeriesHeader.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeDouble(
      5,
      f
    );
  }
  jspb.Message.serializeBinaryExtensions(message, writer,
    proto.mediapipe.TimeSeriesHeader.extensionsBinary, proto.mediapipe.TimeSeriesHeader.prototype.getExtension);
};


/**
 * optional double sample_rate = 1;
 * @return {number}
 */
proto.mediapipe.TimeSeriesHeader.prototype.getSampleRate = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.mediapipe.TimeSeriesHeader} returns this
 */
proto.mediapipe.TimeSeriesHeader.prototype.setSampleRate = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mediapipe.TimeSeriesHeader} returns this
 */
proto.mediapipe.TimeSeriesHeader.prototype.clearSampleRate = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.TimeSeriesHeader.prototype.hasSampleRate = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 num_channels = 2;
 * @return {number}
 */
proto.mediapipe.TimeSeriesHeader.prototype.getNumChannels = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.mediapipe.TimeSeriesHeader} returns this
 */
proto.mediapipe.TimeSeriesHeader.prototype.setNumChannels = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mediapipe.TimeSeriesHeader} returns this
 */
proto.mediapipe.TimeSeriesHeader.prototype.clearNumChannels = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.TimeSeriesHeader.prototype.hasNumChannels = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int32 num_samples = 3;
 * @return {number}
 */
proto.mediapipe.TimeSeriesHeader.prototype.getNumSamples = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.mediapipe.TimeSeriesHeader} returns this
 */
proto.mediapipe.TimeSeriesHeader.prototype.setNumSamples = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mediapipe.TimeSeriesHeader} returns this
 */
proto.mediapipe.TimeSeriesHeader.prototype.clearNumSamples = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.TimeSeriesHeader.prototype.hasNumSamples = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional double packet_rate = 4;
 * @return {number}
 */
proto.mediapipe.TimeSeriesHeader.prototype.getPacketRate = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.mediapipe.TimeSeriesHeader} returns this
 */
proto.mediapipe.TimeSeriesHeader.prototype.setPacketRate = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mediapipe.TimeSeriesHeader} returns this
 */
proto.mediapipe.TimeSeriesHeader.prototype.clearPacketRate = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.TimeSeriesHeader.prototype.hasPacketRate = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional double audio_sample_rate = 5;
 * @return {number}
 */
proto.mediapipe.TimeSeriesHeader.prototype.getAudioSampleRate = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.mediapipe.TimeSeriesHeader} returns this
 */
proto.mediapipe.TimeSeriesHeader.prototype.setAudioSampleRate = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mediapipe.TimeSeriesHeader} returns this
 */
proto.mediapipe.TimeSeriesHeader.prototype.clearAudioSampleRate = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.TimeSeriesHeader.prototype.hasAudioSampleRate = function() {
  return jspb.Message.getField(this, 5) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mediapipe.MultiStreamTimeSeriesHeader.prototype.toObject = function(opt_includeInstance) {
  return proto.mediapipe.MultiStreamTimeSeriesHeader.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mediapipe.MultiStreamTimeSeriesHeader} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mediapipe.MultiStreamTimeSeriesHeader.toObject = function(includeInstance, msg) {
  var f, obj = {
    timeSeriesHeader: (f = msg.getTimeSeriesHeader()) && proto.mediapipe.TimeSeriesHeader.toObject(includeInstance, f),
    numStreams: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mediapipe.MultiStreamTimeSeriesHeader}
 */
proto.mediapipe.MultiStreamTimeSeriesHeader.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mediapipe.MultiStreamTimeSeriesHeader;
  return proto.mediapipe.MultiStreamTimeSeriesHeader.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mediapipe.MultiStreamTimeSeriesHeader} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mediapipe.MultiStreamTimeSeriesHeader}
 */
proto.mediapipe.MultiStreamTimeSeriesHeader.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.mediapipe.TimeSeriesHeader;
      reader.readMessage(value,proto.mediapipe.TimeSeriesHeader.deserializeBinaryFromReader);
      msg.setTimeSeriesHeader(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNumStreams(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mediapipe.MultiStreamTimeSeriesHeader.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mediapipe.MultiStreamTimeSeriesHeader.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mediapipe.MultiStreamTimeSeriesHeader} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mediapipe.MultiStreamTimeSeriesHeader.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimeSeriesHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.mediapipe.TimeSeriesHeader.serializeBinaryToWriter
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional TimeSeriesHeader time_series_header = 1;
 * @return {?proto.mediapipe.TimeSeriesHeader}
 */
proto.mediapipe.MultiStreamTimeSeriesHeader.prototype.getTimeSeriesHeader = function() {
  return /** @type{?proto.mediapipe.TimeSeriesHeader} */ (
    jspb.Message.getWrapperField(this, proto.mediapipe.TimeSeriesHeader, 1));
};


/**
 * @param {?proto.mediapipe.TimeSeriesHeader|undefined} value
 * @return {!proto.mediapipe.MultiStreamTimeSeriesHeader} returns this
*/
proto.mediapipe.MultiStreamTimeSeriesHeader.prototype.setTimeSeriesHeader = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mediapipe.MultiStreamTimeSeriesHeader} returns this
 */
proto.mediapipe.MultiStreamTimeSeriesHeader.prototype.clearTimeSeriesHeader = function() {
  return this.setTimeSeriesHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.MultiStreamTimeSeriesHeader.prototype.hasTimeSeriesHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 num_streams = 2;
 * @return {number}
 */
proto.mediapipe.MultiStreamTimeSeriesHeader.prototype.getNumStreams = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.mediapipe.MultiStreamTimeSeriesHeader} returns this
 */
proto.mediapipe.MultiStreamTimeSeriesHeader.prototype.setNumStreams = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mediapipe.MultiStreamTimeSeriesHeader} returns this
 */
proto.mediapipe.MultiStreamTimeSeriesHeader.prototype.clearNumStreams = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.MultiStreamTimeSeriesHeader.prototype.hasNumStreams = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.mediapipe);
