// source: mediapipe/framework/status_handler.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var mediapipe_framework_mediapipe_options_pb = require('../../mediapipe/framework/mediapipe_options_pb.js');
goog.object.extend(proto, mediapipe_framework_mediapipe_options_pb);
goog.exportSymbol('proto.mediapipe.StatusHandlerConfig', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mediapipe.StatusHandlerConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, proto.mediapipe.StatusHandlerConfig.repeatedFields_, null);
};
goog.inherits(proto.mediapipe.StatusHandlerConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mediapipe.StatusHandlerConfig.displayName = 'proto.mediapipe.StatusHandlerConfig';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.mediapipe.StatusHandlerConfig.repeatedFields_ = [2,1002];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mediapipe.StatusHandlerConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.mediapipe.StatusHandlerConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mediapipe.StatusHandlerConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mediapipe.StatusHandlerConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    statusHandler: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    inputSidePacketList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    externalInputList: (f = jspb.Message.getRepeatedField(msg, 1002)) == null ? undefined : f,
    options: (f = msg.getOptions()) && mediapipe_framework_mediapipe_options_pb.MediaPipeOptions.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mediapipe.StatusHandlerConfig}
 */
proto.mediapipe.StatusHandlerConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mediapipe.StatusHandlerConfig;
  return proto.mediapipe.StatusHandlerConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mediapipe.StatusHandlerConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mediapipe.StatusHandlerConfig}
 */
proto.mediapipe.StatusHandlerConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatusHandler(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addInputSidePacket(value);
      break;
    case 1002:
      var value = /** @type {string} */ (reader.readString());
      msg.addExternalInput(value);
      break;
    case 3:
      var value = new mediapipe_framework_mediapipe_options_pb.MediaPipeOptions;
      reader.readMessage(value,mediapipe_framework_mediapipe_options_pb.MediaPipeOptions.deserializeBinaryFromReader);
      msg.setOptions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mediapipe.StatusHandlerConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mediapipe.StatusHandlerConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mediapipe.StatusHandlerConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mediapipe.StatusHandlerConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getInputSidePacketList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getExternalInputList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1002,
      f
    );
  }
  f = message.getOptions();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      mediapipe_framework_mediapipe_options_pb.MediaPipeOptions.serializeBinaryToWriter
    );
  }
};


/**
 * optional string status_handler = 1;
 * @return {string}
 */
proto.mediapipe.StatusHandlerConfig.prototype.getStatusHandler = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.mediapipe.StatusHandlerConfig} returns this
 */
proto.mediapipe.StatusHandlerConfig.prototype.setStatusHandler = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mediapipe.StatusHandlerConfig} returns this
 */
proto.mediapipe.StatusHandlerConfig.prototype.clearStatusHandler = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.StatusHandlerConfig.prototype.hasStatusHandler = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated string input_side_packet = 2;
 * @return {!Array<string>}
 */
proto.mediapipe.StatusHandlerConfig.prototype.getInputSidePacketList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.mediapipe.StatusHandlerConfig} returns this
 */
proto.mediapipe.StatusHandlerConfig.prototype.setInputSidePacketList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.mediapipe.StatusHandlerConfig} returns this
 */
proto.mediapipe.StatusHandlerConfig.prototype.addInputSidePacket = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.mediapipe.StatusHandlerConfig} returns this
 */
proto.mediapipe.StatusHandlerConfig.prototype.clearInputSidePacketList = function() {
  return this.setInputSidePacketList([]);
};


/**
 * repeated string external_input = 1002;
 * @return {!Array<string>}
 */
proto.mediapipe.StatusHandlerConfig.prototype.getExternalInputList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1002));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.mediapipe.StatusHandlerConfig} returns this
 */
proto.mediapipe.StatusHandlerConfig.prototype.setExternalInputList = function(value) {
  return jspb.Message.setField(this, 1002, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.mediapipe.StatusHandlerConfig} returns this
 */
proto.mediapipe.StatusHandlerConfig.prototype.addExternalInput = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1002, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.mediapipe.StatusHandlerConfig} returns this
 */
proto.mediapipe.StatusHandlerConfig.prototype.clearExternalInputList = function() {
  return this.setExternalInputList([]);
};


/**
 * optional MediaPipeOptions options = 3;
 * @return {?proto.mediapipe.MediaPipeOptions}
 */
proto.mediapipe.StatusHandlerConfig.prototype.getOptions = function() {
  return /** @type{?proto.mediapipe.MediaPipeOptions} */ (
    jspb.Message.getWrapperField(this, mediapipe_framework_mediapipe_options_pb.MediaPipeOptions, 3));
};


/**
 * @param {?proto.mediapipe.MediaPipeOptions|undefined} value
 * @return {!proto.mediapipe.StatusHandlerConfig} returns this
*/
proto.mediapipe.StatusHandlerConfig.prototype.setOptions = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mediapipe.StatusHandlerConfig} returns this
 */
proto.mediapipe.StatusHandlerConfig.prototype.clearOptions = function() {
  return this.setOptions(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.StatusHandlerConfig.prototype.hasOptions = function() {
  return jspb.Message.getField(this, 3) != null;
};


goog.object.extend(exports, proto.mediapipe);
