// source: mediapipe/framework/tool/node_chain_subgraph.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var mediapipe_framework_calculator_pb = require('../../../mediapipe/framework/calculator_pb.js');
goog.object.extend(proto, mediapipe_framework_calculator_pb);
goog.exportSymbol('proto.mediapipe.NodeChainSubgraphOptions', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mediapipe.NodeChainSubgraphOptions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mediapipe.NodeChainSubgraphOptions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mediapipe.NodeChainSubgraphOptions.displayName = 'proto.mediapipe.NodeChainSubgraphOptions';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mediapipe.NodeChainSubgraphOptions.prototype.toObject = function(opt_includeInstance) {
  return proto.mediapipe.NodeChainSubgraphOptions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mediapipe.NodeChainSubgraphOptions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mediapipe.NodeChainSubgraphOptions.toObject = function(includeInstance, msg) {
  var f, obj = {
    nodeType: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    chainLength: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mediapipe.NodeChainSubgraphOptions}
 */
proto.mediapipe.NodeChainSubgraphOptions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mediapipe.NodeChainSubgraphOptions;
  return proto.mediapipe.NodeChainSubgraphOptions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mediapipe.NodeChainSubgraphOptions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mediapipe.NodeChainSubgraphOptions}
 */
proto.mediapipe.NodeChainSubgraphOptions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNodeType(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setChainLength(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mediapipe.NodeChainSubgraphOptions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mediapipe.NodeChainSubgraphOptions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mediapipe.NodeChainSubgraphOptions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mediapipe.NodeChainSubgraphOptions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
};



/**
 * A tuple of {field number, class constructor} for the extension
 * field named `ext`.
 * @type {!jspb.ExtensionFieldInfo<!proto.mediapipe.NodeChainSubgraphOptions>}
 */
proto.mediapipe.NodeChainSubgraphOptions.ext = new jspb.ExtensionFieldInfo(
    167210579,
    {ext: 0},
    proto.mediapipe.NodeChainSubgraphOptions,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.mediapipe.NodeChainSubgraphOptions.toObject),
    0);

mediapipe_framework_calculator_options_pb.CalculatorOptions.extensionsBinary[167210579] = new jspb.ExtensionFieldBinaryInfo(
    proto.mediapipe.NodeChainSubgraphOptions.ext,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.mediapipe.NodeChainSubgraphOptions.serializeBinaryToWriter,
    proto.mediapipe.NodeChainSubgraphOptions.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
mediapipe_framework_calculator_options_pb.CalculatorOptions.extensions[167210579] = proto.mediapipe.NodeChainSubgraphOptions.ext;

/**
 * optional string node_type = 1;
 * @return {string}
 */
proto.mediapipe.NodeChainSubgraphOptions.prototype.getNodeType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.mediapipe.NodeChainSubgraphOptions} returns this
 */
proto.mediapipe.NodeChainSubgraphOptions.prototype.setNodeType = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mediapipe.NodeChainSubgraphOptions} returns this
 */
proto.mediapipe.NodeChainSubgraphOptions.prototype.clearNodeType = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.NodeChainSubgraphOptions.prototype.hasNodeType = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 chain_length = 2;
 * @return {number}
 */
proto.mediapipe.NodeChainSubgraphOptions.prototype.getChainLength = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.mediapipe.NodeChainSubgraphOptions} returns this
 */
proto.mediapipe.NodeChainSubgraphOptions.prototype.setChainLength = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mediapipe.NodeChainSubgraphOptions} returns this
 */
proto.mediapipe.NodeChainSubgraphOptions.prototype.clearChainLength = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.NodeChainSubgraphOptions.prototype.hasChainLength = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * A tuple of {field number, class constructor} for the extension
 * field named `ext`.
 * @type {!jspb.ExtensionFieldInfo<!proto.mediapipe.NodeChainSubgraphOptions>}
 */
proto.mediapipe.NodeChainSubgraphOptions.ext = new jspb.ExtensionFieldInfo(
    167210579,
    {ext: 0},
    proto.mediapipe.NodeChainSubgraphOptions,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.mediapipe.NodeChainSubgraphOptions.toObject),
    0);

mediapipe_framework_calculator_options_pb.CalculatorOptions.extensionsBinary[167210579] = new jspb.ExtensionFieldBinaryInfo(
    proto.mediapipe.NodeChainSubgraphOptions.ext,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.mediapipe.NodeChainSubgraphOptions.serializeBinaryToWriter,
    proto.mediapipe.NodeChainSubgraphOptions.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
mediapipe_framework_calculator_options_pb.CalculatorOptions.extensions[167210579] = proto.mediapipe.NodeChainSubgraphOptions.ext;

goog.object.extend(exports, proto.mediapipe);
