// source: mediapipe/framework/formats/annotation/rasterization.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.mediapipe.Rasterization', null, global);
goog.exportSymbol('proto.mediapipe.Rasterization.Interval', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mediapipe.Rasterization = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.mediapipe.Rasterization.repeatedFields_, null);
};
goog.inherits(proto.mediapipe.Rasterization, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mediapipe.Rasterization.displayName = 'proto.mediapipe.Rasterization';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mediapipe.Rasterization.Interval = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mediapipe.Rasterization.Interval, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mediapipe.Rasterization.Interval.displayName = 'proto.mediapipe.Rasterization.Interval';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.mediapipe.Rasterization.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mediapipe.Rasterization.prototype.toObject = function(opt_includeInstance) {
  return proto.mediapipe.Rasterization.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mediapipe.Rasterization} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mediapipe.Rasterization.toObject = function(includeInstance, msg) {
  var f, obj = {
    intervalList: jspb.Message.toObjectList(msg.getIntervalList(),
    proto.mediapipe.Rasterization.Interval.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mediapipe.Rasterization}
 */
proto.mediapipe.Rasterization.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mediapipe.Rasterization;
  return proto.mediapipe.Rasterization.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mediapipe.Rasterization} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mediapipe.Rasterization}
 */
proto.mediapipe.Rasterization.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.mediapipe.Rasterization.Interval;
      reader.readMessage(value,proto.mediapipe.Rasterization.Interval.deserializeBinaryFromReader);
      msg.addInterval(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mediapipe.Rasterization.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mediapipe.Rasterization.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mediapipe.Rasterization} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mediapipe.Rasterization.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIntervalList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.mediapipe.Rasterization.Interval.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mediapipe.Rasterization.Interval.prototype.toObject = function(opt_includeInstance) {
  return proto.mediapipe.Rasterization.Interval.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mediapipe.Rasterization.Interval} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mediapipe.Rasterization.Interval.toObject = function(includeInstance, msg) {
  var f, obj = {
    y: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    leftX: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    rightX: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mediapipe.Rasterization.Interval}
 */
proto.mediapipe.Rasterization.Interval.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mediapipe.Rasterization.Interval;
  return proto.mediapipe.Rasterization.Interval.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mediapipe.Rasterization.Interval} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mediapipe.Rasterization.Interval}
 */
proto.mediapipe.Rasterization.Interval.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setY(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLeftX(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRightX(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mediapipe.Rasterization.Interval.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mediapipe.Rasterization.Interval.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mediapipe.Rasterization.Interval} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mediapipe.Rasterization.Interval.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * required int32 y = 1;
 * @return {number}
 */
proto.mediapipe.Rasterization.Interval.prototype.getY = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.mediapipe.Rasterization.Interval} returns this
 */
proto.mediapipe.Rasterization.Interval.prototype.setY = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mediapipe.Rasterization.Interval} returns this
 */
proto.mediapipe.Rasterization.Interval.prototype.clearY = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.Rasterization.Interval.prototype.hasY = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required int32 left_x = 2;
 * @return {number}
 */
proto.mediapipe.Rasterization.Interval.prototype.getLeftX = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.mediapipe.Rasterization.Interval} returns this
 */
proto.mediapipe.Rasterization.Interval.prototype.setLeftX = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mediapipe.Rasterization.Interval} returns this
 */
proto.mediapipe.Rasterization.Interval.prototype.clearLeftX = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.Rasterization.Interval.prototype.hasLeftX = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * required int32 right_x = 3;
 * @return {number}
 */
proto.mediapipe.Rasterization.Interval.prototype.getRightX = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.mediapipe.Rasterization.Interval} returns this
 */
proto.mediapipe.Rasterization.Interval.prototype.setRightX = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mediapipe.Rasterization.Interval} returns this
 */
proto.mediapipe.Rasterization.Interval.prototype.clearRightX = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.Rasterization.Interval.prototype.hasRightX = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated Interval interval = 1;
 * @return {!Array<!proto.mediapipe.Rasterization.Interval>}
 */
proto.mediapipe.Rasterization.prototype.getIntervalList = function() {
  return /** @type{!Array<!proto.mediapipe.Rasterization.Interval>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.mediapipe.Rasterization.Interval, 1));
};


/**
 * @param {!Array<!proto.mediapipe.Rasterization.Interval>} value
 * @return {!proto.mediapipe.Rasterization} returns this
*/
proto.mediapipe.Rasterization.prototype.setIntervalList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.mediapipe.Rasterization.Interval=} opt_value
 * @param {number=} opt_index
 * @return {!proto.mediapipe.Rasterization.Interval}
 */
proto.mediapipe.Rasterization.prototype.addInterval = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.mediapipe.Rasterization.Interval, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.mediapipe.Rasterization} returns this
 */
proto.mediapipe.Rasterization.prototype.clearIntervalList = function() {
  return this.setIntervalList([]);
};


goog.object.extend(exports, proto.mediapipe);
